### ISSUE TITLE
akita-cli / userPath = pjson.akitaCli && pjson.akitaCli.basePath ||

### ISSUE THREAD

**Issue by markusgattol** [datorama/akita#142]
I've installed akita-cli using yarn: `yarn global add @datorama/akita-cli`. Now I'm about to start a React project, thereby using akita-cli to set up some templating, but unfortunately to no avail:

```
sa@mbp: /tmp/akita-test  akita
/Users/sa/.config/yarn/global/node_modules/@datorama/akita-cli/plopfile.js:9
  userPath = pjson.akitaCli && pjson.akitaCli.basePath || '';
                   ^

TypeError: Cannot read property 'akitaCli' of undefined
    at module.exports (/Users/sa/.config/yarn/global/node_modules/@datorama/akita-cli/plopfile.js:9:20)
    at nodePlop (/Users/sa/.config/yarn/global/node_modules/node-plop/lib/node-plop.js:250:59)
    at Liftoff.run (/Users/sa/.config/yarn/global/node_modules/plop/src/plop.js:68:15)
    at Liftoff.execute (/Users/sa/.config/yarn/global/node_modules/liftoff/index.js:203:12)
    at module.exports (/Users/sa/.config/yarn/global/node_modules/flagged-respawn/index.js:51:3)
    at Liftoff.<anonymous> (/Users/sa/.config/yarn/global/node_modules/liftoff/index.js:195:5)
    at /Users/sa/.config/yarn/global/node_modules/liftoff/index.js:165:9
    at /Users/sa/.config/yarn/global/node_modules/v8flags/index.js:110:14
    at /Users/sa/.config/yarn/global/node_modules/v8flags/index.js:38:12
    at /Users/sa/.config/yarn/global/node_modules/v8flags/index.js:49:7
sa@mbp: /tmp/akita-test
```

missing types?

**Comment by NetanelBasal** [comment]
How can I reproduce it? react-create-app?

**Comment by markusgattol** [comment]
nope, I just run `akita` from a normal dir created with `mkdir`

**Comment by markusgattol** [comment]
for some reason reinstalling `akita` and `akita-cli` globally fixed the issue
