### ISSUE TITLE
Devtool HMR

### ISSUE THREAD

**Issue by mvrstm** [datorama/akita#244]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When triggered HMR -> page success reload ->get error  -> hmr doesn't work

![akita-error](https://user-images.githubusercontent.com/44908750/60756952-68cba280-a004-11e9-87a0-acdfe990bb6c.png)

<pre><code>
zone.js:703
Unhandled Promise rejection: s.unsubscribe is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: s.unsubscribe is not a function 
    at datorama-akita.js:5328
    at Array.forEach (<anonymous>)
    at akitaDevtools (datorama-akita.js:5324)
    at new AkitaDevtools (datorama-akita-ngdevtools.js:14)
    at _createClass (core.js:18507)
    at _createProviderInstance (core.js:18477)
    at initNgModule (core.js:18410)
    at new NgModuleRef_ (core.js:19137)
    at createNgModuleRef (core.js:19126)
    at Object.debugCreateNgModuleRef [as createNgModuleRef] (core.js:27949) TypeError: s.unsubscribe is not a function
    at http://localhost:4200/vendor.js:115165:29
    at Array.forEach (<anonymous>)
    at akitaDevtools (http://localhost:4200/vendor.js:115161:25)
    at new AkitaDevtools (http://localhost:4200/vendor.js:109650:78)
    at _createClass (http://localhost:4200/vendor.js:76011:20)
    at _createProviderInstance (http://localhost:4200/vendor.js:75981:26)
    at initNgModule (http://localhost:4200/vendor.js:75914:32)
    at new NgModuleRef_ (http://localhost:4200/vendor.js:76641:9)
    at createNgModuleRef (http://localhost:4200/vendor.js:76630:12)
    at Object.debugCreateNgModuleRef [as createNgModuleRef] (http://localhost:4200/vendor.js:85453:12)
</code></pre>

## Environment

<pre><code>
Angular version: 8.1.0

Browser:
- [X] Chrome (desktop) version 75.0.3770.100
 
For Tooling issues:
- Node version: v10.15.1
- Platform:  Windows 10 Pro 64-bit
- @datorama/akita: 4.4.0
- @datorama/akita-ngdevtools: 3.0.2

</code></pre>

HMR setting from the official documentation of Akita and Angular.
https://netbasal.gitbook.io/akita/angular-plugins/hmr
https://github.com/angular/angular-cli/wiki/stories-configure-hmr

**Comment by NetanelBasal** [comment]
Thanks, fixed in the latest version.
