### ISSUE TITLE
Unable to run demo

### ISSUE THREAD

**Issue by Martin-Andersen** [datorama/akita#397]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I am trying to run the the Angular-Ecommerce demo

## Expected behavior

It runs

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://stackblitz.com or similar (you can use this template as a starting point: https://stackblitz.com/github/NetanelBasal/akita-issue-seed).

## What is the motivation / use case for changing the behavior?

➜  angular-ecommerce git:(master) ✗ node_modules/.bin/ng build
Schema validation failed with the following errors:
  Data path ".builders['app-shell']" should have required property 'class'.
Error: Schema validation failed with the following errors:
  Data path ".builders['app-shell']" should have required property 'class'.
    at MergeMapSubscriber._registry.compile.pipe.operators_1.concatMap.validatorResult [as project] (/Users/mha/projects/akita/examples/angular-ecommerce/node_modules/@angular/cli/node_modules/@angular-devkit/core/src/workspace/workspace.js:215:42)
    at MergeMapSubscriber._tryNext (/Users/mha/projects/akita/examples/angular-ecommerce/node_modules/@angular/cli/node_modules/rxjs/internal/operators/mergeMap.js:69:27)
    at MergeMapSubscriber._next (/Users/mha/projects/akita/examples/angular-ecommerce/node_modules/@angular/cli/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (/Users/mha/projects/akita/examples/angular-ecommerce/node_modules/@angular/cli/node_modules/rxjs/internal/Subscriber.js:67:18)
    at MergeMapSubscriber.notifyNext (/Users/mha/projects/akita/examples/angular-ecommerce/node_modules/@angular/cli/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
    at InnerSubscriber._next (/Users/mha/projects/akita/examples/angular-ecommerce/node_modules/@angular/cli/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/Users/mha/projects/akita/examples/angular-ecommerce/node_modules/@angular/cli/node_modules/rxjs/internal/Subscriber.js:67:18)
    at MapSubscriber._next (/Users/mha/projects/akita/examples/angular-ecommerce/node_modules/@angular/cli/node_modules/rxjs/internal/operators/map.js:55:26)
    at MapSubscriber.Subscriber.next (/Users/mha/projects/akita/examples/angular-ecommerce/node_modules/@angular/cli/node_modules/rxjs/internal/Subscriber.js:67:18)
    at SwitchMapSubscriber.notifyNext (/Users/mha/projects/akita/examples/angular-ecommerce/node_modules/@angular/cli/node_modules/rxjs/internal/operators/switchMap.js:86:26)

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10  
- Platform:  Mac latest

Others:

</code></pre>

**Comment by snebjorn** [comment]
Please check out #388 I should have fixed all the demos among other things

**Comment by NetanelBasal** [comment]
@Martin-Andersen any progress here? Try to delete Rx from angular-ecommerce, and install it only in the root repo.

**Comment by NetanelBasal** [comment]
Everything should work with the new structure. Feel free to re-open it if you still have an issue.
