### ISSUE TITLE
localStorage is not defined in universal app with Akita

### ISSUE THREAD

**Issue by amberpew** [datorama/akita#58]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

i'm using the Akita in app with universal rendering and i got error when i try to start the server.

   `> dist\server.js:209400
    storage: localStorage,
             ^
ReferenceError: localStorage is not defined
    at Object.<anonymous> (dist\server.js:209400:14)
    at __webpack_require__ (dist\server.js:20:30)
    at Object.@datorama/akita (dist\server.js:132101:18)
    at __webpack_require__ (dist\server.js:127767:30)
    at Object../src/app/state/app-state.query.ts (dist\server.js:131374:15)
    at __webpack_require__ (dist\server.js:127767:30)
    at Object../src/app/state/index.ts (dist\server.js:131587:10)
    at __webpack_require__ (dist\server.js:127767:30)
    at Object../src/app/app.component.ts (dist\server.js:128687:15)
    at __webpack_require__ (dist\server.js:127767:30)`

I don't use localStorage and persistState. I would appreciate some tips on how to make my app work ^^

## Environment

<pre><code>
Angular version: 6.1.3

**Comment by NetanelBasal** [comment]
I can add protection for node env, but I don't have any way to test it. Can you collaborate?

**Comment by NetanelBasal** [comment]
This is my suggestion:

Add to the persist-store file the following code at the top:
```js
const isNode =
  typeof process !== 'undefined' &&
  process.versions != null &&
  process.versions.node != null;

if(isNode) {
  (global as any).localStorage = { }
}
```

and inside the function itself:

```js
export function persistState(params?: Partial<PersistStateParams>) {
  if(isNode) return;
```

**Comment by zvnt** [comment]
I had the same error with universal rendering and after 1.7.0 it disappeared, but similar error appeared :)

(/** @type {?} */ (localStorage)) = {};
ReferenceError: localStorage is not defined

**Comment by NetanelBasal** [comment]
Let me check.

**Comment by NetanelBasal** [comment]
Deployed a fix in 1.7.1. Verify it with the universal seed.
