### ISSUE TITLE
setError not working properly in Angular

### ISSUE THREAD

**Issue by leopascual** [datorama/akita#803]
### Is this a regression?

No

### Description

Application crash when calling the store set error through a service function called updateErrorState. 
The error is caught properly as a http error response, that we are making on purpose on the backend side (response.status = 500). 

We also tested the set error using a string as parameter and also fails with the same error. 
this.sessionStore.setError('same error'); 

### Please provide the exception or error you saw

```true
ERROR TypeError: Cannot read properties of undefined (reading 'updateErrorState')
    at CatchSubscriber.handleError [as selector] (http.service.ts:154:25)
    at CatchSubscriber.error (catchError.js:27:1)
    at TimeoutWithSubscriber._error (Subscriber.js:75:1)
    at TimeoutWithSubscriber.error (Subscriber.js:55:1)
    at MapSubscriber._error (Subscriber.js:75:1)
    at MapSubscriber.error (Subscriber.js:55:1)
    at FilterSubscriber._error (Subscriber.js:75:1)
    at FilterSubscriber.error (Subscriber.js:55:1)
    at MergeMapSubscriber.notifyError (innerSubscribe.js:45:1)
    at SimpleInnerSubscriber._error (innerSubscribe.js:13:1)
```

### Please provide the environment you discovered this bug in

```true
"@angular/animations": "~12.1.3",
    "@angular/common": "~12.1.3",
    "@angular/compiler": "~12.1.3",
    "@angular/core": "~12.1.3",
    "@angular/forms": "~12.1.3",
    "@angular/localize": "~12.1.3",
    "@angular/platform-browser": "~12.1.3",
    "@angular/platform-browser-dynamic": "~12.1.3",
    "@angular/router": "~12.1.3",
    "@datorama/akita": "^6.2.1",
    "@datorama/akita-ng-entity-service": "^6.1.1",
    "@ng-bootstrap/ng-bootstrap": "^10.0.0",
    "bootstrap": "^4.5.0",
    "rxjs": "~6.6.0",
    "swiper": "^8.0.5",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.4"
```

### Do you want to create a pull request?

No

**Comment by leopascual** [comment]
AGGHhh!!! 

Needs to be in the subscription as error callback and not inside the pipe catcherror of the observable definition.
